require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  NewCops: enable

RSpec:
  Enabled: true

Performance:
  Enabled: true

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Metrics/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - '**/*.gemspec'

Layout/IndentationConsistency:
  EnforcedStyle: normal

Style/BlockDelimiters:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/FilePath:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false
